set -g default-terminal "screen-256color"
set -as terminal-overrides ',*:Tc'
set -g mouse on
set -g set-clipboard on
bind -n PageUp copy-mode -u
bind -n PageDown send-keys PageDown
bind-key j choose-tree -Z

set -g window-active-style bg="#000000"
set -g window-style bg="#1C1C1C"
set -g pane-border-style fg=colour240       # Inactive pane border (grey)
set -g pane-active-border-style fg=colour10 # Active pane border (green)

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'armando-rios/tmux'

# armando-rios/tmux status bar configuration
set -g @tmux_theme "mocha"
set -g @tmux_status_show_cwd "on"
set -g @tmux_status_show_sysinfo "on"
set -g @tmux_status_show_clock "on"
set -g @tmux_status_format "cwd|sysinfo|clock"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
