set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'
set -as terminal-overrides ',*:UTF-8'
set -g mouse on
set -g set-clipboard on
set -g pane-border-status top
#set -g pane-border-format "#{?pane_active,#[fg=colour75],#[fg=colour240]} #{pane_index} #{pane_current_command} #{b:pane_current_path} "
set -g pane-border-format "#{?pane_active,#[fg=colour75],#[fg=colour240]} #{?#{==:#{pane_index},0},⓪,#{?#{==:#{pane_index},1},①,#{?#{==:#{pane_index},2},②,#{?#{==:#{pane_index},3},③,#{?#{==:#{pane_index},4},④,#{?#{==:#{pane_index},5},⑤,#{?#{==:#{pane_index},6},⑥,#{?#{==:#{pane_index},7},⑦,#{?#{==:#{pane_index},8},⑧,#{?#{==:#{pane_index},9},⑨,#{?#{==:#{pane_index},10},⑩,#{pane_index}}}}}}}}}}}} #{pane_current_command} #{b:pane_current_path} "


bind -n PageUp copy-mode -u
bind -n PageDown send-keys PageDown
bind-key j choose-tree -Z

set -g window-active-style bg="#000000"
set -g window-style bg="#1C1C1C"
set -g pane-border-style fg=colour240       # Inactive pane border (grey)
set -g pane-active-border-style fg=colour10 # Active pane border (green)

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'armando-rios/tmux'

# armando-rios/tmux status bar configuration
set -g @tmux_theme "mocha"
set -g @tmux_status_show_cwd "on"
set -g @tmux_status_show_sysinfo "on"
set -g @tmux_status_show_clock "on"
set -g @tmux_status_format "cwd|sysinfo|clock"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
